# SwiftLint <https://realm.github.io/SwiftLint/>
#
check_for_updates: false

excluded:
  - build

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - line_length
  - nesting
  - no_fallthrough_only
  - todo
  - trailing_comma
  - trailing_newline
  - type_body_length

identifier_name:
  min_length: 1
  allowed_symbols: ["_"]
  excluded:
    - Core.*

type_name:
  min_length: 2
  allowed_symbols: ["_"]
  excluded:
    - iOS_.*

function_parameter_count:
  warning: 6

large_tuple:
  warning: 3
